VERSION = "V10"
GENOME_STRING = "V10-{strategy}-{rep-weighting}-{prob-defect}"

PAYOFF_COOP = 2
PAYOFF_DAGA = -2
PAYOFF_DDON = 4
PAYOFF_DBOT = -1
PAYOFF_DECL = 0

N_AGENTS = 100
TRANS_PER_AGENT = 150

TOP_X = 25
GENERATIONS_TO_DO = 10

INITIAL_HAWK = 150

DEBUG = True
VERBOSE_SIMULATION = True
VERBOSE_SIMULATION_N = 7500

GENETICS_STRATEGY_HAWK_DOM = 100
GENETICS_STRATEGY_MUTATE = 75

GENETICS_REP_WEIGHTING_RAND_MIN = -92
GENETICS_REP_WEIGHTING_RAND_MAX = 92

GENETICS_PROB_DEFECT_RAND_MIN = -92
GENETICS_PROB_DEFECT_RAND_MAX = 92
