VERSION = "V10"
GENOME_STRING = "V10-{strategy}-{rep-weighting}-{prob-defect}"

PAYOFF_COOP = 2
PAYOFF_DAGA = -2
PAYOFF_DDON = 4
PAYOFF_DBOT = -1
PAYOFF_DECL = 0

N_AGENTS = 150
TRANS_PER_AGENT = 500

TOP_X = 30
GENERATIONS_TO_DO = 25

INITIAL_HAWK = 150

DEBUG = True
VERBOSE_SIMULATION = True
VERBOSE_SIMULATION_N = 50000
